# Generated by Django 2.0.4 on 2018-04-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_account', models.CharField(blank=True, max_length=32, null=True, verbose_name='账号')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '云平台账号',
                'verbose_name_plural': '云平台账号',
            },
        ),
        migrations.CreateModel(
            name='CloudDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='云硬盘')),
                ('disk_uuid', models.CharField(blank=True, max_length=128, null=True, verbose_name='云硬盘uuid')),
                ('disk_size', models.CharField(blank=True, max_length=32, null=True, verbose_name='云硬盘空间')),
            ],
            options={
                'verbose_name': '云主机磁盘信息',
                'verbose_name_plural': '云主机磁盘信息',
            },
        ),
        migrations.CreateModel(
            name='CloudNic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_name', models.CharField(blank=True, max_length=64, verbose_name='网卡名')),
                ('netmask', models.CharField(blank=True, max_length=64, verbose_name='掩码')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
            ],
            options={
                'verbose_name': '云主机网卡信息',
                'verbose_name_plural': '云主机网卡信息',
            },
        ),
        migrations.CreateModel(
            name='CloudOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='云平台')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '云平台',
                'verbose_name_plural': '云平台',
            },
        ),
        migrations.CreateModel(
            name='CloudProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='项目名')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CloudAccount', verbose_name='所属云账号')),
            ],
            options={
                'verbose_name': '云平台项目',
                'verbose_name_plural': '云平台项目',
            },
        ),
        migrations.CreateModel(
            name='CloudServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='主机名')),
                ('uuid', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='云主机uuid')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='内网IP')),
                ('float_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='浮动IP')),
                ('os_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统')),
                ('vcpu', models.IntegerField(blank=True, null=True)),
                ('memory_total', models.CharField(blank=True, max_length=32, null=True)),
                ('money', models.CharField(blank=True, max_length=32, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Asset')),
                ('cloud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.CloudOperator', verbose_name='所属云')),
                ('cloud_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.CloudProject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '云主机信息',
                'verbose_name_plural': '云主机信息',
            },
        ),
        migrations.RemoveField(
            model_name='physicalserver',
            name='os_version',
        ),
        migrations.AlterField(
            model_name='physicalserver',
            name='os_platform',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='cloudnic',
            name='cloud_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.CloudServer'),
        ),
        migrations.AddField(
            model_name='clouddisk',
            name='cloud_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.CloudServer'),
        ),
        migrations.AddField(
            model_name='cloudaccount',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CloudOperator', verbose_name='所属云'),
        ),
    ]
