# Generated by Django 2.0.4 on 2018-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='monment',
            field=models.TextField(blank=True),
        ),
    ]
