# Generated by Django 2.0.4 on 2018-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_monment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
