# Generated by Django 2.0.4 on 2018-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userinfo_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限信息表', 'verbose_name_plural': '权限信息表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色信息表', 'verbose_name_plural': '角色信息表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '登录用户信息表', 'verbose_name_plural': '登录用户信息表'},
        ),
    ]
